### ISSUE TITLE
heightmap not rendered in editor

### ISSUE THREAD

**Issue by swenner** [Calinou/awesome-godot#1]
The heightmap works fine when I press play, but it is not drawn in the editor. Is this a known limitation or a bug? I'm running Godot master.

**Comment by Calinou** [comment]
You should ask the original author about it in [this topic](http://www.godotengine.org/forum/viewtopic.php?f=14&t=1630), it was initially featured in Add Primitives.

**Comment by swenner** [comment]
Okay, thanks.
