### ISSUE TITLE
[Suggestion] I found that the Godot Game Tools is very useful

### ISSUE THREAD

**Issue by damvcoool** [Calinou/awesome-godot#112]
More infor here:
https://viniguerrero.itch.io/godot-game-tools

Available Features 
- Batch Animations Bake In A Single File
- Character Armature Clean and Fixes for Better Export
- Animations Testing 
- Add Automatic Root Motion For Model Export 
- Automated NLA Tracks Insertion
- Animation Rename
- Tileset Generation (With Navigation and Collision Shape)
- Tileset Export to Godot Game Engine
- Root Motion Sample Project
- Texture Baking For Mixamo Characters (WIP)

**Comment by Calinou** [comment]
Sounds good to me. However, I couldn't find a license attached to the add-on. I made an issue to request it: https://github.com/vini-guerrero/Godot_Game_Tools/issues/21

Once a license is added, I'll add this to awesome-godot.
