### ISSUE TITLE
FontAwesome plugin link is dead

### ISSUE THREAD

**Issue by junpeikun** [Calinou/awesome-godot#129]
FontAwesome plugin link points to a 404 page.

**Comment by Calinou** [comment]
@Geequlim Are there any plans to publish it and update this plugin for Godot 3.2? If not, that's fine. Let me know and I'll remove it from the list.

**Comment by Calinou** [comment]
I removed the FontAwesome plugin from the list in 79c39a02906be848540fb3af75d8ab1dc82c3dea, closing.
