### ISSUE TITLE
Game Dev Center Channel to Video Tutorials

### ISSUE THREAD

**Issue by ghost** [Calinou/awesome-godot#145]
Suggestion to add the Game Development Center channel to video tutorials

With 60 tutorials up, currently building on the well-received multiplayer dedicated server series. I would like to suggest the Game Development Center channel be added to the video tutorial list.

Game Development Center[https://www.youtube.com/c/GameDevelopmentCenter] Godot 2D and multiplayer game development (Godot 3.x)

Disclaimer for transparency: I'm the owner of the GDC channel

**Comment by jkgenser** [comment]
> 

Hey @Stefan-GameDev : Are you able to post the code for your tutorials on Github? Would be very helpful to have reference outside of the videos.

**Comment by Kun-guru** [comment]
> > 
> 
> Hey @Stefan-GameDev : Are you able to post the code for your tutorials on Github? Would be very helpful to have reference outside of the videos.

I totally agree with this... sometimes I wish I could scroll the video to see the code 8)
