### ISSUE TITLE
Add Godot GamePad plugin

### ISSUE THREAD

**Issue by ghost** [Calinou/awesome-godot#180]
[Godot GamePad](https://github.com/ACB-prgm/Godot_GamePad) allows players to use there mobile devices as controllers

**Comment by Calinou** [comment]
I couldn't find a license, so I requested the author to add a license: https://github.com/ACB-prgm/Godot_GamePad/issues/4

**Comment by Calinou** [comment]
@Independent-Eye2446 MIT license has been added, feel free to open a pull request to add this :slightly_smiling_face:
