### ISSUE TITLE
New Plugin: AutoColliders

### ISSUE THREAD

**Issue by graycastle** [Calinou/awesome-godot#244]
Submitting a newly published plugin at https://github.com/graycastle/godot-AutoColliders, organized under Plugins and scripts in the Various Godot versions section:

[AutoColliders](https://github.com/graycastle/godot-AutoColliders) - Plugin that enabled the automatic generation of CollisionPolygon2D nodes from a sprite's opaque pixels. Expected expansion into 3D mesh collision generation. (Godot 3.x)

**Comment by Calinou** [comment]
Isn't this already available as a built-in feature of the editor since Godot 3.2? Select a Sprite node, then choose **Sprite > Create CollisionPolygon2D Sibling** at the top of the 2D editor viewport:

![image](https://user-images.githubusercontent.com/180032/168925109-1c84c0fe-9d4d-4684-9449-6918be012c49.png)

This is also already available in 3D when selecting a MeshInstance, using a similar menu at the top of the 3D viewport.

**Comment by graycastle** [comment]
Hey there @Calinou, there is an option to convert just the sprite texture to a collision object, as you showed, but this implementation includes live updates to the sibling when the properties of the Sprite change (in-editor and with the ability to trigger regeneration at runtime), as well as adding the ability to add space (padding) to the collider around the sprite's shape.

Plugin just aimed to build off of that foundation and add some things I've found useful (or have been requested). That said, if it's not unique enough for inclusion on the list, no worries at all!

**Comment by Calinou** [comment]
> Hey there @Calinou, there is an option to convert just the sprite texture to a collision object, as you showed, but this implementation includes live updates to the sibling when the properties of the Sprite change (in-editor and with the ability to trigger regeneration at runtime), as well as adding the ability to add space (padding) to the collider around the sprite's shape.
> 
> Plugin just aimed to build off of that foundation and add some things I've found useful (or have been requested). That said, if it's not unique enough for inclusion on the list, no worries at all!

In this case, this add-on looks useful enough to me :slightly_smiling_face: 

Could you reopen the [pull request](https://github.com/godotengine/awesome-godot/pull/243) that was accidentally closed (or open a new PR)?

**Comment by Calinou** [comment]
Implemented by https://github.com/godotengine/awesome-godot/pull/245.
