### ISSUE TITLE
UniversalSky 404 not found

### ISSUE THREAD

**Issue by azur-wolve** [Calinou/awesome-godot#253]
on the addon list:

[Universal Sky](https://github.com/7leodev/UniversalSky) - Adds a Dynamic Sky and Time of Day.

**Comment by Calinou** [comment]
I removed it from the list in https://github.com/godotengine/awesome-godot/commit/3337c573a813daeda2253b58836eaf1ff1d0c5ac, as the author appears to have deleted their GitHub account. Thanks for the report :slightly_smiling_face:
