### ISSUE TITLE
add GodotReport to Website category 

### ISSUE THREAD

**Issue by huyhoang160593** [Calinou/awesome-godot#262]
The website [This Week in Godot](https://thisweekingodot.com/) is no longer make new issues start from April based on this tweet: https://twitter.com/ThisWeekInGodot/status/1510729093565796356. And Kaiju has start his own report in https://www.thegodotreport.com/ . Please add this to the Website category

**Comment by Calinou** [comment]
I replaced This Week in Godot by The Godot Report with https://github.com/godotengine/awesome-godot/commit/bba41be4aa3cd1677afbd39da2ab4283e671cbf4.
