### ISSUE TITLE
Submitting a project for Godot 4 possible yet?

### ISSUE THREAD

**Issue by lesleyrs** [Calinou/awesome-godot#268]
Hello I want to submit an open source tool I made in Godot but it's made for Godot 4 only. Is it possible to add a new Godot 4 tab or are they not being accepted yet?

Edit: nvm I saw a 4.0 module listed.

**Comment by Calinou** [comment]
Indeed, you can submit 4.0 projects, templates and add-ons :slightly_smiling_face:
