### ISSUE TITLE
XSM - worth adding ?

### ISSUE THREAD

**Issue by atngames** [Calinou/awesome-godot#272]
Hi,

I did code XSM, a complete State Machine plugin with Parallel states, Loops, Random States, easy animation launch and so on.

DO you thing it could enter this awesome list ?

fr godot 3 and 4:
https://godotengine.org/asset-library/asset/1504
https://godotengine.org/asset-library/asset/1546

Thanks for your work,
atn

**Comment by tavurth** [comment]
@atngames just make a PR :)

**Comment by atngames** [comment]
done thanks ;)
#278
