### ISSUE TITLE
Include Importality - graphics and animations importers fot Godot 4.x

### ISSUE THREAD

**Issue by nklbdev** [Calinou/awesome-godot#291]
Hello! 

There are many great projects on your list!  I want to suggest adding my project to it.  This is an addon that adds several import plugins to Godot.

About it:

Exports from:
- **Aseprite/LibreSprite** (app integration)
- **Krita** (app integration)
- **Pencil2D** (app integration)
- **Piskel** (independent parser)
- **Pixelorama** (independent parser)

Imports to:
- **Regular images**
- **Sprite Sheet** (JSON resource without stored text, but with all the information in the "data" property)
- **SpriteFrames**
- **AnimatedSprite2D**/**3D**
- **Sprite2D**/**3D** or **TextureRect** animated with AnimationPlayer

And it can [import any other formats](https://github.com/nklbdev/godot-4-importality/wiki/importing-as-regular-images-(en)) as regular images by calling external command line utilities.

Be sure to read the Wiki in the repository - there is a lot of useful information, especially about complex integration with Krita.

Available at:
- [Godot Asset Library](https://godotengine.org/asset-library/asset/2025)
- [GitHib](https://github.com/nklbdev/godot-4-importality)

[Demo on YouTube](https://youtu.be/tlfhlQPr_IA) (without sound, only subtitles)

**Comment by Calinou** [comment]
Feel free to open a pull request for this :slightly_smiling_face:

**Comment by nklbdev** [comment]
Wow, unexpected! I thought that I would run into some difficulties)))
Thanks, I'll create a pull request today.

**Comment by nklbdev** [comment]
Thank you!
