### ISSUE TITLE
I want to provide some game development plug-ins for Godot using c#, but I don't know how Godot supports .net?

### ISSUE THREAD

**Issue by TimeToTheNorth** [Calinou/awesome-godot#297]
I want to provide some game development plug-ins for Godot using c#, but I don't know how Godot supports .net?

**Comment by Calinou** [comment]
Yes, Godot has C# support in both Godot 3.x and 4.x :slightly_smiling_face: 

https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html

However, awesome-godot only accepts Godot add-ons, not "generic" C# libraries that are not specific to Godot.
