### ISSUE TITLE
add WonderDraft & DungeonDraft?

### ISSUE THREAD

**Issue by jsonkody** [Calinou/awesome-godot#299]
Isn't WonderDraft and DungeonDraft both made in Godot?
They seems like quite awesome pieces and would be nice showcase of what is Godot capable of.

**Comment by Calinou** [comment]
In GitHub's open source spirit, this list only accepts open source projects (so you can learn from the projects' code).

While Wonderdraft and Dungeondraft are made with Godot, they are unfortunately not open source. Therefore, we cannot accept them on this list. If you are looking to refer other users to high-quality projects made with Godot, check out the [Showcase page](https://godotengine.org/showcase/). Dungeondraft is already on that page :slightly_smiling_face:
