### ISSUE TITLE
Projects to assess and potentially include

### ISSUE THREAD

**Issue by akien-mga** [Calinou/awesome-godot#34]
(TODO list of things to try and see if they would be worth adding to the curated list. The criteria to be included in the list are not precisely defined, but I guess if a game is very simple (e.g. basically similar to an existing demo, like a simple pong implementation), we probably don't want to include it)

2D games:
- [Breakable](https://github.com/didier-v/breakable) - Breakout-like game
- [Grow!](https://github.com/FEDE0D/grow-ludum-dare-34) - Endless mazes! Run against the clock and find the exit.
- [Nightwatch](https://github.com/JKGiih/nightwatch)
- [Simple 2D RPG](https://github.com/vnen/godot-rpg2d)
- [SnakeGodot](https://github.com/yichen0831/SnakeGodot) - A simple Snake game
- [Space Shooter](https://github.com/Paulb23/godot_space_shooter)
- [Sorcerer Puzzle](https://github.com/henriquelalves/godot-sorcerer-puzzle) - Small puzzle prototype based on the Tower of the Sorcerer
- [Star-Game](https://github.com/DCowboy/Star-Game)
- [Tetris](https://github.com/yichen0831/TetrisGodot) - A simple Tetris game
- [Virus Defense](https://github.com/cporras/virusDefence) - Didactic tower defence game
- [Watch arbitrary numbers go up](https://github.com/YeOldeDM/wangu) - A Godot GUI experiment // no license specified yet

3D games:
- [C-Plan Tracker](https://github.com/khairul169/cplan-tracker) - Multiplayer FPS game using the GDNet module for networking
- [Horror FPS](https://github.com/khairul169/godot-horror-fps)

Demos:
- [Camera raycasting](https://github.com/oxrock/Godot-camera-raycasting-demo)

Plugins and scripts:
- [Dialogue tree tool](https://github.com/StraToN/godot-dialogtreetools) - Tool for creating dialog trees for Adventure or RPG games
- [Networking library](https://github.com/KOBUGE-Games/gdscript-networking-library) - KOBUGE's Godot networking library
- [ShapeTrails2D](https://github.com/sergicollado/godotShapeTrails2D) - Scripts and scene components to make Trails2D

**Comment by henriquelalves** [comment]
I just created a GGJ game using Godot, and finished a last bug-fixing commit. If you want, you might check if it's a nice addition to the list, I'll be glad to help!

https://github.com/henriquelalves/Chaos

**Comment by rolfpancake** [comment]
This youtube playlist gave me some nice insight in what is possible:
[adolson - Godot Engine Games](https://www.youtube.com/playlist?list=PL9i2bb2OUKCACptlUgO20di75FUAVfCn7)
(With links to the corresponding websites or even repos this would add a visualy appealing rescource.)

**Comment by akien-mga** [comment]
Also quite interesting: https://github.com/henriquelalves/GodotTIE
https://github.com/TeddyDD/Gravity-Hates-You

I'll try to browse through this list during the week-end and add the missing stuff.

**Comment by TeddyDD** [comment]
https://github.com/khairul169/cheese-hunter This is nice 2.5D
and this https://github.com/henriquelalves/Chaos

**Comment by impmja** [comment]
I recently ported Robert Penner's equations for easing over to Godot Script. Maybe it is to use for someone here or even for the list. Cheers.

Here it is: [Godot Easing](https://github.com/impmja/godot-easing)

**Comment by Xananax** [comment]
I'd like to submit the following plugins (not mine, and no affiliation):

The awesome Platform2D plugin by Rod Zilla, that allows to create non-linear 2D terrain:
https://github.com/RodZill4/godot-platform2d ([demo](https://www.youtube.com/watch?v=mE4TJGSGUD4))

The cool Asset Dropper by Andreas Esau, that facilitates art-based 2D map editing 
https://github.com/ndee85/asset_dropper ([demo](https://www.youtube.com/watch?v=ovaSj38j5Vw))

The fantastic Cutout Animation tools, which is half Blender, but exports 2D rigged and deformable characters to Godot and thus acts as a free Spine/Spriter replacement (imho this is HUGE):
https://github.com/ndee85/coa_tools ([demo](https://www.youtube.com/watch?v=uoQZV1f_J1s))

The point and click framework Escoria:
https://github.com/godotengine/escoria ([announcement post](https://godotengine.org/article/our-point-click-framework-finally-out))

**Comment by TeddyDD** [comment]
> The point and click framework Escoria:

#56

**Comment by kakoeimon** [comment]
I just created a pluging : https://github.com/kakoeimon/GodotMation it is for internal game economy. Please check it out.

**Comment by TheSHEEEP** [comment]
I created a module that allows very fast collision checking with boxes, spheres and cylinders independent of Godot's physics world: 
https://github.com/TheSHEEEP/godotccd

**Comment by Calinou** [comment]
@TheSHEEEP Added in https://github.com/Calinou/awesome-godot/commit/ef55c1ab354ac5570684d37011fab5b0e251d7fb :slightly_smiling_face:

**Comment by winston-yallow** [comment]
I made a [Cutscene Script](https://github.com/winston-yallow/godot-cutscenes) and a [Tokenizer](https://github.com/winston-yallow/gd-tokenizer) in GDScript.

I am not sure if they would fit into this list as they are rather small.

**Comment by nezvers** [comment]
[GameTemplate](https://github.com/nezvers/Godot-GameTemplate) It's close for me to call it a finished base version.
[Sealed Bite](https://github.com/securas/SealedBite) is an awesome game by @securas.
[GitHub integration](https://github.com/fenix-hub/godot-engine.github-integration) in Godot.

**Comment by Calinou** [comment]
@nezvers Added in https://github.com/Calinou/awesome-godot/commit/35e74df0e9ae4ea04f0a521e6ff422aea1df7b6a, https://github.com/Calinou/awesome-godot/commit/e3ce7f7f33007c25815847e1f768c3b012ec2a98 and https://github.com/Calinou/awesome-godot/commit/74700a8c5fc341f400cef8242ef998b3b62779bb :slightly_smiling_face:

**Comment by HeadClot** [comment]
I came across this awesome tool via the Godot Discord. 

https://github.com/kyzfrintin/Godot-Mixing-Desk

**Comment by Calinou** [comment]
@HeadClot Added in https://github.com/Calinou/awesome-godot/commit/1e953d1f9039cb22038c460a96af6e9e8c7c0288.

**Comment by kyzfrintin** [comment]
Hey @Calinou, thanks for adding my plugin! I'm so proud right now.

**Comment by nezvers** [comment]
I have a fair amount of example projects that I'm going to turn into video tutorials - https://github.com/nezvers/Godot_3.1_Public_Examples
Also, there's a good amount of games made in Trijams (3h game jams but some are done longer than 3h) Playable at nezvers.itch.io - https://github.com/nezvers/Godot_jam_games_3.1

**Comment by asheraryam** [comment]
I open sourced one of my jam games recently so it would be cool to have it listed.

Repo: https://gitlab.com/shared-games/lurking-in-the-dark
Binaries: https://asheraryam.itch.io/lurking-in-the-dark

GMTK Winners Video with timestamp: https://youtu.be/o-WrQ77zUvA&t=16m10s

**Comment by Scony** [comment]
https://github.com/Scony/godot-gdscript-toolkit is pretty stable right now, so may be worth to mention.

**Comment by TheSHEEEP** [comment]
Another self-plug from me:
https://github.com/TheSHEEEP/godotdetour

Navigation library for 3.2 using recast + detour.

**Comment by Calinou** [comment]
@TheSHEEEP Added in https://github.com/Calinou/awesome-godot/commit/ffa515e7359fbd4707a2abbe608fa754ea071333.

**Comment by TheSHEEEP** [comment]
Updated my godotccd to 3.2. (3.1 has become a tag)
Looking at the versions, this is only going to get more confusing, especially once 4.0 (and further ones...) come out.

Markdown does support tables:
https://help.github.com/en/github/writing-on-github/organizing-information-with-tables

Maybe an idea to make use of that to make it a bit more readable.

**Comment by Calinou** [comment]
@TheSHEEEP I updated godotccd's supported Godot versions in https://github.com/Calinou/awesome-godot/commit/d17d439f5b76bbb44636a8a9aaead9081c23a174.

About using a table format, I looked at [other awesome lists](https://github.com/sindresorhus/awesome#readme) but I can't see any that use a table format. Some lists use inline images or special characters for each item, but that's about it. I'm afraid using a table format may hurt readability on narrow displays or mobile devices.

**Comment by ghost** [comment]
I'd like to propose the addition of my template framework, which provides an ability to load Godot projects as `Core` mod, and also allows to load/unload `Mod` projects without polluting original `Core`. I have been working on for ~3 months now, and there are a lot of cool features that could also be used for completely procedural (Minecraft-Rimworld like) content/system driven multiplayer games:
https://github.com/unaryinc/Unary_Common

**Comment by 1shevelov** [comment]
- [HeartBeast's channel](https://www.youtube.com/user/uheartbeast) - A Godot developers's diary and tutorials. (Godot 3.x)
(The developer is good and active and his channel has 136k subscribers)

**Comment by Calinou** [comment]
@1shevelov Added in https://github.com/Calinou/awesome-godot/commit/badbb929e6be3a3dc79434b75a2f5d8248300579.

**Comment by Kehom** [comment]
I hope it's OK to "advertise" my work here. I have a web page with (for now just a few) tutorials at http://kehomsforge.com
And I also have an addon pack (pure GDScript) that can be found at https://github.com/Kehom/GodotAddonPack
This pack includes a networking addon that automates most of the process to achieve synchronized network multiplayer games with snapshots. On my web page there are instructions to use this addon plus how to get client side prediction working.

**Comment by realkotob** [comment]
@Kehom Excellent resource! I found your tutorials useful last year when I was diving into networking in godot, and the new stuff looks even more impressive!

**Comment by ryliejamesthomas** [comment]
Wasn't sure which section to put it in, so didn't do a PR, but—

https://github.com/arcadia-unity/ArcadiaGodot | http://selfsamegames.com/pages/posts/arcadia-godot.html

—looks cool. It integrates Clojure into Godot.

**Comment by Calinou** [comment]
@ryliejamesthomas I think it'd be better to add it to [godot-lang-support](https://github.com/Vivraan/godot-lang-support) instead. That repository has much more details and does a better job at showcasing third-party language bindings.

**Comment by ryliejamesthomas** [comment]
Oh ta, wasn't aware of that.

**Comment by Calinou** [comment]
I added a link to godot-lang-support in the README in https://github.com/godotengine/awesome-godot/commit/b6f5cc2b25786c759201074b1a7570976360be7d.

**Comment by Calinou** [comment]
Closing this issue, as it's better to open new individual issues (or pull requests) to add more projects to the list. This keeps the discussion more structured :slightly_smiling_face: 

PS: If you know how to open a pull request, you don't need to open an issue first. Just open a pull request directly.
