### ISSUE TITLE
Reorganize by latest compatible major Godot version?

### ISSUE THREAD

**Issue by svetogam** [Calinou/awesome-godot#343]
I think this list could be organized better. Here are a few problems with the current organization:

* The version given for a project gets outdated quickly as projects upgrade to newer versions.
* There's a big lumpy section for "Various Godot versions" that makes other sections seem pointless.

My solution is to simplify versioning to only tell the *latest compatible major Godot version*. This means having just the sections "Godot 4", "Godot 3", and "Godot 2" for versions.

The idea behind this is that it's much easier to upgrade minor versions than major versions, so readers can usually assume that projects will be compatible with the latest minor version of a major version. Exceptions can be found by looking at that particular project, instead of being given here.

For plugins that support multiple versions in weird ways, they should give this information like they already do in the "Various Godot versions" blob section. Since precise version compatibility is more important for plugins, they can optionally give more specific versions like "Godot 4.2+" in the same way.

Benefits:

* It will be easier for contributors to decide where each item should go and for readers looking for something specific to tell where it can be found.
* It will be easier to keep the list up-to-date.
* It will better emphasize the difference between major versions, which is the most relevant version information.
* It will look nicer by having fewer sections which are consistent across the list.

Downsides:

* Plugins that are compatible with both Godot 4 and Godot 3 will be found under Godot 4, which is unintuitive. To mitigate this problem, it could explicitly say "Sorted by latest compatible major Godot version" for plugins.

---

# Example

## Games

*Open Source Games that use Godot.*

#### Godot 4

* Game A - asdf.
* Game B - asdf.
* Game C - asdf.

#### Godot 3

* Game D - asdf.
* Game E - asdf.
* Game F - asdf.

#### Godot 2

* Game G - asdf.
* Game H - asdf.
* Game I - asdf.

## Plugins and scripts

*Scripts that let you do new stuff, or enhance Godot functionality. (Sorted by latest compatible major Godot version.)*

#### Godot 4

* Plugin A - asdf.
* Plugin B - asdf (Godot 3.x, 4.x).
* Plugin C - asdf (Godot 4.2+).

#### Godot 3

* Plugin D - asdf (Godot 3.0).
* Plugin E - asdf (Godot 2.x, 3.x).
* Plugin F - asdf.

#### Godot 2

* Plugin G - asdf.
* Plugin H - asdf.
* Plugin I - asdf.

**Comment by Calinou** [comment]
Given how [Godot's version compatibility](https://docs.godotengine.org/en/latest/about/release_policy.html#what-are-the-criteria-for-compatibility-across-engine-versions) works nowadays, it makes sense to have unified categories for Godot 4.x and 3.x.

Assets that are only compatible with Godot 2.x could be removed by now, given they are unlikely to be useful nowadays (since very few users are still on 2.x).

**Comment by svetogam** [comment]
I can make a pull request doing this, but there's a few issues to clear up first.

1. Should the headers read, for example, "Godot 4" or "Godot 4.x"? I would prefer "Godot 4" because it's simpler and the ".x" is irrelevant information. But if Godot Engine has a convention to say "Godot 4.x" instead then that will be fine.
2. Since many items show out-of-date versions, I would keep the existing claims about versions without updating them in this PR, to not just modify everything and potentially introduce mistakes. A different PR can update them.
3. In the first post, I suggested that submitted plugins can optionally give specific version information, but now I think even this option should be removed. I think it would be a waste of time and effort to duplicate this information, which the Godot Asset Library keeps much better. So I will strip a lot of the existing version information in this PR.
4. I will keep Godot 2 items and categories. Removing them can be done in a different PR. I would personally like to see them kept around somewhere, whether in the main branch or in a legacy branch or archive, but I think this is a different issue.

Should I go ahead with my preferences here, or do you have anything to add?

**Comment by Calinou** [comment]
> Should the headers read, for example, "Godot 4" or "Godot 4.x"? I would prefer "Godot 4" because it's simpler and the ".x" is irrelevant information. But if Godot Engine has a convention to say "Godot 4.x" instead then that will be fine.

I agree, "Godot 4" makes more sense to me.

> Since many items show out-of-date versions, I would keep the existing claims about versions without updating them in this PR, to not just modify everything and potentially introduce mistakes. A different PR can update them.

Yes, please keep them as-is for now.

> In the first post, I suggested that submitted plugins can optionally give specific version information, but now I think even this option should be removed. I think it would be a waste of time and effort to duplicate this information, which the Godot Asset Library keeps much better. So I will strip a lot of the existing version information in this PR.

I agree it makes sense to remove the Godot version mentioned between parentheses next to each asset.

> I will keep Godot 2 items and categories. Removing them can be done in a different PR. I would personally like to see them kept around somewhere, whether in the main branch or in a legacy branch or archive, but I think this is a different issue.

That makes sense. Keep them in the PR and I'll see what to do next.

**Comment by antimundo** [comment]
In my personal opinion, the most useful projects from this list, are the ones that still work in the lastest versions of its branch.

When I use Godot 3, I always use the last available version (3.5.3 or 3.6rc) but I rarely use 3.0, 3.1, 3.2, 3.3, 3.4...
The same way, nowdays I always use 4.3 or 4.2, I rarely use the original older 4.0, 4.1...

So I like this proposal, I think it would easier to read, and more useful if users can asume that the projects listed under "Godot 4" will work on the last stable version of the Godot 4 branch.

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/awesome-godot/pull/349, closing.

> So I like this proposal, I think it would easier to read, and more useful if users can asume that the projects listed under "Godot 4" will work on the last stable version of the Godot 4 branch.

[Version compatibility](https://docs.godotengine.org/en/latest/about/release_policy.html) since 3.5 is much better, so most add-ons developed for 4.0 onwards will keep working in 4.3 (4.1 onwards for GDExtensions).
