### ISSUE TITLE
Starcatcher game

### ISSUE THREAD

**Issue by ghost** [Calinou/awesome-godot#362]
Actually I am not sure if it should be added so I am creating issues https://github.com/Escada-Games/starcatcher-jam because assets aren't uploaded... Code is there but it will be difficult without assets...

**Comment by Calinou** [comment]
Without assets, it's not possible to run the project locally, so I don't think it has good educational use.

If assets are not available for legal reasons, then the project author could create a script that extracts assets from the PCK and places them in the right locations so the project can be imported and run locally. [gdsdecomp](https://github.com/bruvzg/gdsdecomp) can be useful here.
