### ISSUE TITLE
add my color Picker plugin

### ISSUE THREAD

**Issue by TeddyDD** [Calinou/awesome-godot#6]
https://github.com/TeddyDD/godot-ColorPicker
Simple plugin for Godot game engine It makes easy to generate Color class constructors for use in your code.

**Comment by akien-mga** [comment]
It's already included :)

_Edit:_ It was added 2 hours, by @Calinou forgot to close this issue manually, or better, add "Fixes #6" in the commit log.

**Comment by TeddyDD** [comment]
ok, closing now
