### ISSUE TITLE
add Couple-quest

### ISSUE THREAD

**Issue by Clonewayx** [Calinou/awesome-godot#61]
https://github.com/Clonewayx/Couple-quest GPL-3.0

Simple "board-like" game for couples.

**Comment by pwab** [comment]
The new projects home seems to be https://github.com/Couple-quest/Couple-quest accordig to your PR #62.

I'm not sure this should be on the list for three reasons:

- The project doesn't seem to be mature enough (see UI)
- The code files are only partly written in english language so the projects way of implementing its functionalities can't be understand by most of the people
- The filestructure of the project is flat

This project could be added to the [Godots Showcase](https://godotengine.org/showcase) but I'm not a fan of adding it to an awesome list.

**Comment by Calinou** [comment]
Closing per @pwab's comment.
