### ISSUE TITLE
Add links to published games

### ISSUE THREAD

**Issue by pwab** [Calinou/awesome-godot#67]
The games list should contain published (and therefore polished) games from Steam/Play Store/Apple Store. This could be done by a simple link to the store - for example:

- **Satellite Repairman** - _Some description_ [[Steam]](http://store.steampowered.com/app/567780/Satellite_Repairman/)

**Comment by TeddyDD** [comment]
> A curated list of **free/libre** games, plugins, add-ons and scripts for Godot.

**Comment by pwab** [comment]
Well your are right, this issue was just a proposal to extend the provided information here. If this repo is strictly based on free/libre stuff, than this is not the right place for these kind of links.

**Comment by TeddyDD** [comment]
Well, that's up to @Calinou to decide if we want to non-libre stuff here. Personally I don't mind as long as they are properly marked. On the other hand I think better place for commercial games is https://godotengine.org/showcase
