### ISSUE TITLE
General Game Dev Information

### ISSUE THREAD

**Issue by dardub** [Calinou/awesome-godot#71]
Would it be a good idea to have resources for game development in general?

Godot is my first game engine and as someone who has programming experience but new to game dev, it's quite confusing to know which tools to use and really where to start.

**Comment by akien-mga** [comment]
You mean like https://github.com/Calinou/awesome-gamedev ? :)

**Comment by dardub** [comment]
Uh Yes! ...

Put that at the top of awesome-godot!  :D

**Comment by Calinou** [comment]
> Put that at the top of awesome-godot! :D

Adding a few related pages at the bottom of the list is OK to me, but probably not at the top.

**Comment by Calinou** [comment]
I'll close this, as I intend this list to focus on Godot-specific resources. There are many other websites and Awesome lists that focus on general game development resources out there :slightly_smiling_face:
