### ISSUE TITLE
Add gd-com npm library

### ISSUE THREAD

**Issue by Tilican** [Calinou/awesome-godot#72]
Hi,
Can you add the gd-com npm library ? 
This is a lib to make connection between udp / tcp with nodejs :)

**Comment by akien-mga** [comment]
What's the link with Godot? Website, source repo?

**Comment by Calinou** [comment]
Done: https://github.com/Calinou/awesome-godot/commit/94bc6c37bc9fcddd0fb63de8f778771aa487f166

**Comment by Tilican** [comment]
Hi,
The gd-com package change from https://github.com/tilican/gd-com to https://github.com/gd-com
