### ISSUE TITLE
Change gd-com npm package link

### ISSUE THREAD

**Issue by Tilican** [Calinou/awesome-godot#88]
HI,
The gd-com package change from https://github.com/tilican/gd-com to https://github.com/gd-com and also his npm package got splitted so this https://www.npmjs.com/package/gd-com isn't the right link.

Thx

**Comment by Calinou** [comment]
Which packages should be linked on awesome-godot? I see `tcp`, `utils` and `udp` (currently empty) on [gd-com](https://github.com/gd-com).

**Comment by Tilican** [comment]
it's better to link the github (https://github.com/gd-com), i will add the npm package link to the github :+1:

**Comment by Calinou** [comment]
I think it would be better to link directly to packages which can be useful in their current state, even if it means having several entries in awesome-godot (which is fine to me).

**Comment by Tilican** [comment]
Can you change gd-com link to : https://www.npmjs.com/package/@gd-com/utils pls ?
