### ISSUE TITLE
KidsCanCode

### ISSUE THREAD

**Issue by Duroxxigar** [Calinou/awesome-godot#95]
I believe that you should add KidsCanCode to your list of video tutorials.

https://www.youtube.com/channel/UCNaPQ5uLX5iIEHUCLmfAgKg

**Comment by Duroxxigar** [comment]
PR #96 created

**Comment by Calinou** [comment]
Added in https://github.com/Calinou/awesome-godot/commit/6c51a152631aa0726dfff71ed7767225fc7ce9a1.
